# mysql-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: d29yZHByZXNz  # "wordpress" in base64
  MYSQL_DATABASE: d29yZHByZXNz       # "wordpress" in base64
  MYSQL_USER: d29yZHByZXNz           # "wordpress" in base64
  MYSQL_PASSWORD: d29yZHByZXNz       # "wordpress" in base64
  DATA_SOURCE_NAME: d29yZHByZXNzOndvcmRwcmVzc0B0Y3AobXlzcWwtc2VydmljZS5kZWZhdWx0LnN2Yy5jbHVzdGVyLmxvY2FsOjMzMDYpL3dvcmRwcmVzcw==  # Updated
