apiVersion: v1
kind: Secret
metadata:
  name: mysqld-exporter-config
  namespace: monitoring
type: Opaque
data:
  .my.cnf: W2NsaWVudF0KdXNlcj13b3JkcHJlc3MKcGFzc3dvcmQ9d29yZHByZXNzCmhvc3Q9bXlzcWwtc2VydmljZS5kZWZhdWx0LnN2Yy5jbHVzdGVyLmxvY2FsCg==
